### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by Gengar-lab** [Mrmaxmeier/BombSquad-Community-Mod-Manager#65] opened 2019-02-02 16:00 UTC
@Mrmaxmeier Please close unwanted issues that others created.

**Comment by MattZ45986** [comment] 2019-02-05 02:18
@Benefit-Zebra, I hope you'll understand that the Issues page is a sort of FAQ for users who want to  find an answer to their questions.  Personally, I know it has helped me very much.  The purpose of leaving issues open is to 1) spark helpful answers to maybe ongoing issues and 2) expose others to important pieces of information concerning the repository and essentially the whole process of modding the game.  Thus, closing "unwanted" issues would keep others from easily finding useful information.  Though it is a bit messier, it does have a purpose.

I will, however, close this issue, as it is more of a general Github concern than a particular Bombsquad concern.  (Also, some friendly advice: don't just name the issue   "Please"  , though it's polite.  It gives readers no insight as to what the issue is about.)

**Closed as completed by MattZ45986** 2019-02-05 02:18 UTC
